# Generated by Django 4.1.7 on 2023-03-30 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answeroption_question_questiondiagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightedword',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlightedword', to='api.question'),
        ),
        migrations.AlterField(
            model_name='questiondiagram',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_diagram', to='api.question'),
        ),
    ]
