# Generated by Django 4.1.7 on 2023-03-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_highlightedword_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondiagram',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='diagram_image',
            field=models.ImageField(blank=True, null=True, upload_to='diagrams/'),
        ),
        migrations.AddField(
            model_name='question',
            name='highlight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='HighlightedWord',
        ),
        migrations.DeleteModel(
            name='QuestionDiagram',
        ),
    ]
