# Generated by Django 4.1.7 on 2023-04-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_questiondiagram_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ManyToManyField(to='api.subject'),
        ),
    ]
